### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by huntrar** [neelkamath/xkcd-downloader#1]
Fails after downloading up to Mycology from April 2016.

`Traceback (most recent call last):
  File "downloader.py", line 35, in <module>
    urllib.request.urlretrieve(data["img"], name)
  File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`

**Comment by neelkamath** [comment]
Found it. Comic 404 doesn't exist. I believe this is so as the server requires this number explicitly. Comics 403 etc. are fine though.
